"""Pipeline orchestrator: read log → parse → assess → facts.json + report."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from . import (
    assessment,
    log_parser,
    model_inspect,
    recommendations,
    report_generator,
)
from . import (
    comparison as comparison_mod,
)
from . import facts as facts_mod
from .safe_io import read_text_safe

log = logging.getLogger(__name__)


@dataclass
class AnalysisOptions:
    output_dir: Path | None = None
    language: str = "en"
    lp_file: Path | None = None
    baseline_log: Path | None = None


def run_analysis(log_file: str | Path, options: AnalysisOptions) -> Path:
    log_path = Path(log_file)
    if not log_path.exists():
        raise FileNotFoundError(f"Log file not found: {log_path}")
    text = read_text_safe(log_path)
    if text is None:
        raise RuntimeError(f"Could not read log file: {log_path}")

    parsed = log_parser.parse_log(text)
    if not parsed.get("termination") and not parsed.get("sizes"):
        raise RuntimeError(
            f"{log_path} does not look like a Gurobi log "
            "(no 'Optimize a model with …' or termination lines found)."
        )

    model_info = model_inspect.inspect_model(options.lp_file) if options.lp_file else None
    if options.lp_file and model_info is None:
        log.warning("model file %s could not be analyzed; continuing log-only", options.lp_file)

    result = assessment.assess(parsed, model_info)

    comparison = None
    if options.baseline_log:
        btext = read_text_safe(options.baseline_log)
        if btext:
            comparison = comparison_mod.compare(
                log_parser.parse_log(btext), parsed, str(options.baseline_log)
            )
        else:
            log.warning("baseline log %s could not be read; skipping comparison",
                        options.baseline_log)

    settings = recommendations.collect_settings(result["findings"])
    meta = {
        "log_file": str(log_path),
        "language": options.language,
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
    }
    facts = facts_mod.build_facts(parsed, result, meta, model_info)
    facts["recommended_settings"] = settings
    if comparison:
        facts["comparison"] = comparison

    output_dir = options.output_dir or _default_output_dir(log_path)
    report_path, facts_path = report_generator.write_outputs(
        facts, log_path, output_dir, options.language
    )
    _write_prm(settings, output_dir, log_path.stem)
    log.info("report: %s", report_path)
    log.info("facts:  %s", facts_path)
    return report_path


def _write_prm(settings: dict[str, str], output_dir: Path, stem: str) -> Path | None:
    """Write the recommended parameters as a Gurobi .prm file the user can load
    with model.read('<file>.prm'). Returns the path, or None if no settings."""
    if not settings:
        return None
    prm_path = output_dir / f"{stem}_recommended.prm"
    lines = ["# Recommended Gurobi parameters — generated by the solve_tuning skill.",
             f"# Apply in gurobipy with: model.read('{prm_path.name}')",
             "# (Gurobi's PRM format: one 'ParameterName value' per line.)"]
    lines += [f"{param} {value}" for param, value in settings.items()]
    prm_path.write_text("\n".join(lines) + "\n")
    return prm_path


def _default_output_dir(log_path: Path) -> Path:
    """Write under the run's ``debug/`` ancestor when present (matching the
    result-explanation skill), else next to the log."""
    for parent in log_path.parents:
        if parent.name == "debug":
            return parent / "solve_tuning"
    return log_path.parent / "solve_tuning_report"
