"""Output-language resolution + message catalog for the deterministic parts of
the solve-tuning report (mirrors the result-explanation skill's i18n).

Language is resolved on the CLI (explicit ``--lang`` ▸ OS locale ▸ English) and
threaded into ``meta['language']`` so the summarizer narrates in the same
language. Parameter names, numbers, and warning text pass through verbatim.
"""

from __future__ import annotations

import os
from typing import Final

SUPPORTED_LANGUAGES: Final[tuple[str, ...]] = ("en", "ja")
DEFAULT_LANGUAGE: Final[str] = "en"
_LOCALE_ENV_VARS: Final[tuple[str, ...]] = ("LC_ALL", "LC_MESSAGES", "LANG", "LANGUAGE")


def resolve_language(explicit: str | None = None) -> str:
    if explicit is not None and explicit.strip().lower() not in ("", "auto"):
        return _normalize(explicit)
    for var in _LOCALE_ENV_VARS:
        value = os.environ.get(var)
        if value and value.strip().lower().startswith("ja"):
            return "ja"
    return DEFAULT_LANGUAGE


def _normalize(value: str) -> str:
    normalized = value.strip().lower()
    if normalized in SUPPORTED_LANGUAGES:
        return normalized
    if normalized.startswith("ja"):
        return "ja"
    return DEFAULT_LANGUAGE


_CATALOG: Final[dict[str, dict[str, str]]] = {
    "report_title": {"en": "Solve-Tuning Report", "ja": "求解チューニングレポート"},
    "generated_label": {"en": "Generated", "ja": "生成日時"},
    "explanation_header": {"en": "Assessment", "ja": "診断"},
    "tech_details_summary": {
        "en": "Technical details (log overview, coefficient ranges, warnings, termination, "
              "recommended parameters — click to expand)",
        "ja": "技術詳細（ログ概要・係数レンジ・警告・終了状態・推奨パラメータ — クリックで展開）",
    },
    "report_footer": {
        "en": "Generated by the `solve_tuning` skill.",
        "ja": "`solve_tuning` スキルにより生成。",
    },
    "regen_note": {
        "en": "> _※ This summary was carried over from a prior run. The technical sections below were regenerated by the latest run._",
        "ja": "> _※ このサマリは過去の実行から引き継いだものです。技術セクション（以下の技術詳細）は最新の実行で再生成されています。_",
    },
    "placeholder": {
        "en": "> Verdict / Why / What To Change are produced by the summarizer subagent. Run `/solve-tuning <log>` via Claude Code to populate this section. When run from the bare CLI the report contains only this placeholder and the technical details below.",
        "ja": "> 診断 / 原因 / 変更すべき点 はサマライザのサブエージェントが生成します。Claude Code から `/solve-tuning <log>` を実行するとこのセクションが埋まります。CLI 単体での実行ではこのプレースホルダと以下の技術詳細のみになります。",
    },
    # Log overview
    "overview_header": {"en": "Log overview", "ja": "ログ概要"},
    "ov_version": {"en": "Gurobi version", "ja": "Gurobi バージョン"},
    "ov_model": {"en": "Model", "ja": "モデル"},
    "ov_model_value": {
        "en": "{rows} rows, {cols} columns, {nz} nonzeros{mip}",
        "ja": "{rows} 行, {cols} 列, {nz} 非ゼロ{mip}",
    },
    "mip_suffix": {"en": " (MIP)", "ja": "（MIP）"},
    "ov_status": {"en": "Termination status", "ja": "終了状態"},
    "ov_objective": {"en": "Best objective", "ja": "最良目的関数値"},
    "ov_bound": {"en": "Best bound", "ja": "最良限界"},
    "ov_gap": {"en": "Gap", "ja": "ギャップ"},
    "ov_runtime": {"en": "Runtime", "ja": "実行時間"},
    "ov_work": {"en": "Work units", "ja": "ワークユニット"},
    "ov_nodes": {"en": "Nodes explored", "ja": "探索ノード数"},
    # Coefficient stats
    "coeff_header": {"en": "Coefficient statistics", "ja": "係数統計"},
    "coeff_table_header": {
        "en": "| Part | Range (min, max) | Ratio | Assessment |",
        "ja": "| 部位 | レンジ (最小, 最大) | 比率 | 評価 |",
    },
    "coeff_ok": {"en": "ok", "ja": "良好"},
    "coeff_monitor": {"en": "monitor", "ja": "要注意"},
    "coeff_risk": {"en": "numerical risk", "ja": "数値リスク"},
    "coeff_high_risk": {"en": "HIGH risk — reformulate", "ja": "高リスク — 再定式化推奨"},
    # Warnings
    "warnings_header": {"en": "Warnings", "ja": "警告"},
    "no_warnings": {"en": "No warnings printed in the log.", "ja": "ログに警告はありません。"},
    # Findings / recommendations
    "findings_header": {"en": "Findings", "ja": "所見"},
    "recommendations_header": {"en": "Recommended changes", "ja": "推奨される変更"},
    "rec_table_header": {
        "en": "| Parameter | Change | Why |",
        "ja": "| パラメータ | 変更 | 理由 |",
    },
    "rec_formulation": {"en": "(formulation)", "ja": "（定式化）"},
    # Model structure (from the .lp/.mps file)
    "model_header": {"en": "Model structure (from the model file)", "ja": "モデル構造（モデルファイル由来）"},
    "model_class": {"en": "Model class", "ja": "モデルの分類"},
    "model_linear_yes": {"en": "linear (LP) — the fastest class", "ja": "線形（LP）— 最速の分類"},
    "model_linear_no": {"en": "not purely linear", "ja": "純粋な線形ではない"},
    "model_density": {"en": "Matrix density", "ja": "行列の密度"},
    "model_gen_breakdown": {"en": "General constraints", "ja": "一般制約"},
    "model_objsense": {"en": "Objective sense", "ja": "目的関数の向き"},
    "model_special": {
        "en": "Quadratic constraints: {q}, SOS: {s}, general constraints: {g}",
        "ja": "二次制約: {q}, SOS: {s}, 一般制約: {g}",
    },
    "model_extreme": {
        "en": "Extreme matrix coefficients: largest {hv:g} on `{hvar}` in `{hc}`; smallest {lv:g} on `{lvar}` in `{lc}`.",
        "ja": "係数の極値: 最大 {hv:g}（`{hc}` の `{hvar}`）; 最小 {lv:g}（`{lc}` の `{lvar}`）。",
    },
    "coeff_source_note": {
        "en": "_Ranges taken from the {src}._",
        "ja": "_レンジは{src}から取得。_",
    },
    "src_model": {"en": "model file (exact)", "ja": "モデルファイル（厳密）"},
    "src_log": {"en": "log", "ja": "ログ"},
    # Applyable settings artifact
    "apply_header": {"en": "Apply these settings", "ja": "推奨設定の適用"},
    "apply_intro": {
        "en": "Drop-in parameter settings (also written to `{prm}`):",
        "ja": "そのまま使えるパラメータ設定（`{prm}` にも出力）:",
    },
    # Two-log comparison
    "compare_header": {"en": "Comparison vs baseline", "ja": "ベースラインとの比較"},
    "compare_intro": {
        "en": "Baseline: `{file}`",
        "ja": "ベースライン: `{file}`",
    },
    "compare_table_header": {
        "en": "| Metric | Baseline | Current | Change |",
        "ja": "| 指標 | ベースライン | 今回 | 変化 |",
    },
    "presolve_header": {"en": "Presolve", "ja": "プリソルブ"},
    "presolve_line": {
        "en": "Removed {rr} rows / {rc} columns; presolved model {pr} rows, {pc} columns, {pnz} nonzeros.",
        "ja": "{rr} 行 / {rc} 列を削除。プリソルブ後: {pr} 行, {pc} 列, {pnz} 非ゼロ。",
    },
    "nondefault_header": {"en": "Non-default parameters set", "ja": "設定された非デフォルトパラメータ"},
}


def tr(language: str, key: str, **kwargs: object) -> str:
    lang = language if language in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE
    entry = _CATALOG[key]
    template = entry.get(lang) or entry[DEFAULT_LANGUAGE]
    return template.format(**kwargs) if kwargs else template


def has(key: str) -> bool:
    return key in _CATALOG


def all_translations(key: str) -> set[str]:
    entry = _CATALOG[key]
    return {entry[lang] for lang in SUPPORTED_LANGUAGES if lang in entry}
