import Foundation

/// Generates per-file notes, a repo index, and a machine-readable graph JSON.
/// All output lives under `repoRoot/.code-notes/`.
///
///   .code-notes/
///     index.md          ← whole-repo summary ranked by impact (LLM reads first)
///     graph.json        ← machine-readable adjacency list for tooling
///     notes/            ← one .md per code file
public enum CodeNoteWriter {

    // MARK: - Public entry points

    /// Generate CGNode values for the graph AND write all artifacts to disk.
    public static func generateNoteNodes(scan: ScanResult, repoRoot: URL) -> [CGNode] {
        let notesRoot = repoRoot.appendingPathComponent(".code-notes/notes", isDirectory: true)
        try? FileManager.default.createDirectory(at: notesRoot, withIntermediateDirectories: true)

        let usedBy    = buildUsedBy(scan: scan)
        let codeFiles = scan.files.filter { $0.language != "markdown" && $0.language != "other" }

        let nodes: [CGNode] = codeFiles.compactMap { file -> CGNode? in
            let content = noteMarkdown(path: file.path, scan: scan, usedBy: usedBy)
            let noteURL = notesRoot.appendingPathComponent(file.path + ".md")
            try? FileManager.default.createDirectory(
                at: noteURL.deletingLastPathComponent(), withIntermediateDirectories: true)
            try? content.write(to: noteURL, atomically: true, encoding: .utf8)

            let noteRelPath = ".code-notes/notes/\(file.path).md"
            return CGNode(
                id: "note:\(file.path)",
                title: (file.path as NSString).lastPathComponent + ".md",
                kind: .docPage,
                position: .zero,
                metadata: [
                    "source_file":      noteRelPath,
                    "fileURL":          noteURL.absoluteString,
                    "language":         "markdown",
                    "source_code_file": file.path,
                    "note_content":     content
                ]
            )
        }

        writeIndex(scan: scan, usedBy: usedBy, repoRoot: repoRoot)
        writeGraphJSON(scan: scan, usedBy: usedBy, repoRoot: repoRoot)
        return nodes
    }

    // MARK: - Note markdown

    public static func noteMarkdown(path: String, scan: ScanResult, usedBy: [String: [String]]) -> String {
        let entry   = scan.files.first { $0.path == path }
        let lang    = entry?.language ?? "unknown"
        let loc     = entry?.loc ?? 0
        let symbols = scan.symbols[path] ?? []
        let imports = scan.imports[path] ?? []
        let role    = inferRole(path: path, language: lang)
        let deps    = (usedBy[path] ?? []).sorted()

        var out: [String] = []

        out.append("# \((path as NSString).lastPathComponent)")
        out.append("")
        out.append("| Field | Value |")
        out.append("|-------|-------|")
        out.append("| **Path** | `\(path)` |")
        out.append("| **Language** | \(lang) |")
        out.append("| **Lines** | \(loc) |")
        out.append("| **Role** | \(role) |")
        out.append("")

        // Imports
        if !imports.isEmpty {
            out.append("## Imports")
            out.append("")
            out.append("| Module | Kind |")
            out.append("|--------|------|")
            for imp in imports.sorted() {
                let isInternal = scan.files.contains { $0.path == imp }
                out.append("| `\((imp as NSString).lastPathComponent)` | \(isInternal ? "internal" : "external") |")
            }
            out.append("")
        }

        // Types
        let types = symbols.filter { $0.kind == "class" }
        if !types.isEmpty {
            out.append("## Types")
            out.append("")
            out.append("| Name | Line | Declaration |")
            out.append("|------|------|-------------|")
            for t in types {
                let decl = t.declaration.map { "`\($0)`" } ?? "`\(t.name)`"
                out.append("| `\(t.name)` | L\(t.line) | \(decl) |")
            }
            out.append("")
        }

        // Functions
        let funcs = symbols.filter { $0.kind == "function" }
        if !funcs.isEmpty {
            out.append("## Functions")
            out.append("")
            out.append("| Name | Line | Signature |")
            out.append("|------|------|-----------|")
            for f in funcs {
                let sig = f.declaration.map { "`\($0)`" } ?? "`\(f.name)`"
                out.append("| `\(f.name)` | L\(f.line) | \(sig) |")
            }
            out.append("")
        }

        // Used by
        if !deps.isEmpty {
            out.append("## Used By")
            out.append("")
            for d in deps {
                out.append("- `\((d as NSString).lastPathComponent)`")
            }
            out.append("")
        }

        out.append("---")
        out.append("*Auto-generated by GraphKit · regenerate with Generate Graph*")

        return out.joined(separator: "\n")
    }

    // MARK: - index.md

    static func writeIndex(scan: ScanResult, usedBy: [String: [String]], repoRoot: URL) {
        let codeDir = repoRoot.appendingPathComponent(".code-notes")
        try? FileManager.default.createDirectory(at: codeDir, withIntermediateDirectories: true)

        let codeFiles = scan.files.filter { $0.language != "markdown" && $0.language != "other" }
        let langs     = Array(Set(codeFiles.map { $0.language })).sorted().joined(separator: ", ")

        var out: [String] = []
        out.append("# Codebase Index")
        out.append("")
        out.append("| Field | Value |")
        out.append("|-------|-------|")
        out.append("| **Files** | \(codeFiles.count) |")
        out.append("| **Languages** | \(langs) |")
        out.append("| **Total lines** | \(codeFiles.reduce(0) { $0 + $1.loc }) |")
        out.append("")

        // High-impact files ranked by number of dependents
        let ranked = codeFiles
            .map { f -> (ScanResult.FileEntry, Int) in (f, usedBy[f.path]?.count ?? 0) }
            .sorted { $0.1 > $1.1 }
            .prefix(20)

        out.append("## High-Impact Files")
        out.append("> Files most depended on — change these with care.")
        out.append("")
        out.append("| File | Role | Used By | Functions |")
        out.append("|------|------|---------|-----------|")
        for (f, depCount) in ranked where depCount > 0 {
            let role  = inferRole(path: f.path, language: f.language)
            let fns   = scan.symbols[f.path]?.filter { $0.kind == "function" }.count ?? 0
            out.append("| `\((f.path as NSString).lastPathComponent)` | \(role) | \(depCount) | \(fns) |")
        }
        out.append("")

        // Files grouped by role
        let byRole = Dictionary(grouping: codeFiles) { inferRole(path: $0.path, language: $0.language) }
        out.append("## Files by Role")
        out.append("")
        for (role, roleFiles) in byRole.sorted(by: { $0.key < $1.key }) {
            let files = roleFiles.sorted { $0.path < $1.path }
            out.append("### \(role) (\(files.count) files)")
            out.append("")
            for f in files {
                let fns = scan.symbols[f.path]?.filter { $0.kind == "function" }.count ?? 0
                out.append("- `\(f.path)` — \(f.loc) lines, \(fns) functions")
            }
            out.append("")
        }

        out.append("---")
        out.append("*Auto-generated by GraphKit · regenerate with Generate Graph*")

        try? out.joined(separator: "\n")
            .write(to: codeDir.appendingPathComponent("index.md"), atomically: true, encoding: .utf8)
    }

    // MARK: - graph.json

    static func writeGraphJSON(scan: ScanResult, usedBy: [String: [String]], repoRoot: URL) {
        let codeDir = repoRoot.appendingPathComponent(".code-notes")

        struct FileNode: Encodable {
            let path: String
            let name: String
            let language: String
            let loc: Int
            let role: String
            let imports: [String]
            let usedBy: [String]
            let types: [SymEntry]
            let functions: [SymEntry]
        }
        struct SymEntry: Encodable {
            let name: String
            let line: Int
            let declaration: String?
        }

        let codeFiles = scan.files.filter { $0.language != "markdown" && $0.language != "other" }
        let nodes: [FileNode] = codeFiles.map { f in
            let syms  = scan.symbols[f.path] ?? []
            let types = syms.filter { $0.kind == "class"    }.map { SymEntry(name: $0.name, line: $0.line, declaration: $0.declaration) }
            let funcs = syms.filter { $0.kind == "function" }.map { SymEntry(name: $0.name, line: $0.line, declaration: $0.declaration) }
            return FileNode(
                path:      f.path,
                name:      (f.path as NSString).lastPathComponent,
                language:  f.language,
                loc:       f.loc,
                role:      inferRole(path: f.path, language: f.language),
                imports:   (scan.imports[f.path] ?? []).sorted(),
                usedBy:    (usedBy[f.path] ?? []).sorted(),
                types:     types,
                functions: funcs
            )
        }

        struct Graph: Encodable {
            let version: String
            let summary: Summary
            let files: [FileNode]
        }
        struct Summary: Encodable {
            let totalFiles: Int
            let totalEdges: Int
        }

        let totalEdges = scan.imports.values.reduce(0) { $0 + $1.count }
        let graph = Graph(version: "1.0",
                          summary: Summary(totalFiles: codeFiles.count, totalEdges: totalEdges),
                          files: nodes)
        let enc = JSONEncoder(); enc.outputFormatting = [.prettyPrinted, .sortedKeys]
        if let data = try? enc.encode(graph) {
            try? data.write(to: codeDir.appendingPathComponent("graph.json"), options: .atomic)
        }
    }

    // MARK: - Helpers

    /// Invert scan.imports to get: filePath → [files that import it]
    public static func buildUsedBy(scan: ScanResult) -> [String: [String]] {
        var usedBy: [String: [String]] = [:]
        for (importer, targets) in scan.imports {
            for target in targets {
                usedBy[target, default: []].append(importer)
            }
        }
        return usedBy
    }

    public static func inferRole(path: String, language: String) -> String {
        let lower    = path.lowercased()
        let filename = (path as NSString).lastPathComponent.lowercased()
        if filename.contains("test")                                    { return "Test" }
        if filename.hasSuffix("viewmodel.swift")                        { return "ViewModel" }
        if filename.hasSuffix("view.swift") ||
           filename.hasSuffix("panel.swift") ||
           filename.hasSuffix("sheet.swift") ||
           filename.hasSuffix("screen.swift")                           { return "View" }
        if filename.hasSuffix("service.swift")                          { return "Service" }
        if filename.hasSuffix("store.swift") ||
           filename.hasSuffix("repository.swift")                       { return "Store" }
        if filename.hasSuffix("client.swift")                           { return "Client" }
        if filename.hasSuffix("error.swift") ||
           filename.hasSuffix("errors.swift")                           { return "Error" }
        if filename.hasSuffix("model.swift")                            { return "Model" }
        if filename.hasSuffix("router.swift") ||
           filename.hasSuffix("coordinator.swift")                      { return "Router" }
        if lower.contains("/viewmodels/")                               { return "ViewModel" }
        if lower.contains("/views/")                                    { return "View" }
        if lower.contains("/models/")                                   { return "Model" }
        if lower.contains("/services/")                                 { return "Service" }
        if lower.contains("/persistence/")                              { return "Persistence" }
        if lower.contains("/infrastructure/")                           { return "Infrastructure" }
        if lower.contains("/codegraph/")                                { return "CodeGraph" }
        if language == "typescript" || language == "javascript"         { return "Web" }
        return "Module"
    }
}
