import Foundation

/// Writes `system/memory/environment.md`: this machine's runtime facts for a
/// project — virtualenv, the PATH dirs verify commands get, project/lock
/// files, top-level folders.
///
/// The server's repo-memory reader (`extension/graphkit/memory.mjs`,
/// `repoMemoryBlock`) already injects `system/memory/` into every chat agent
/// turn and serves it through v2's `project_memory` tool, so this file is how
/// the local agents learn "how do I run this here?" without spending tool
/// calls rediscovering it. Core, not a feature: the note must exist in every
/// build profile, including the ones with Loop and Graph compiled out.
///
/// NOTE: machine-specific by nature, so it is never committed — the memory
/// folder's self-ignoring `.gitignore` covers it, and this writer adds that
/// marker when no generator has yet.
public enum EnvironmentNoteWriter {
    static let fileName = "environment.md"

    /// Marker files reported per ecosystem, in display order.
    static let pythonFiles = ["pyproject.toml", "setup.py", "setup.cfg", "requirements.txt",
                              "uv.lock", "poetry.lock", "Pipfile.lock", ".python-version"]
    static let nodeFiles = ["package.json", "package-lock.json", "pnpm-lock.yaml", "yarn.lock",
                            "bun.lockb", ".nvmrc"]
    static let swiftFiles = ["Package.swift"]

    /// Folders never listed as project layout (tooling, not structure;
    /// `system/` is LLM-IDE's own state).
    static let hiddenFolders: Set<String> = ["node_modules", "venv", "__pycache__", "build", "dist", "system"]

    /// The note for the repo at `repoRoot` inside the project at `projectRoot`.
    ///
    /// - Postcondition: deterministic for the same files and `inherited`
    ///   (no timestamp), so `write` can skip an unchanged note; `$HOME` is
    ///   shown as `~`, never as an absolute path.
    public static func render(projectRoot: URL, repoRoot: URL, inherited: [String: String]) -> String {
        let home = inherited["HOME"] ?? NSHomeDirectory()
        func display(_ path: String) -> String {
            path.hasPrefix(home + "/") ? "~" + path.dropFirst(home.count) : path
        }
        var lines = ["# Runtime environment",
                     "_Generated by LLM-IDE on this machine — do not edit. Verify and test commands the app runs (Loop, Auto Task) use this environment._",
                     ""]
        lines.append("- Repository: `\(relativePath(of: repoRoot, under: projectRoot))`")
        if let venv = ProjectRuntimeEnvironment.virtualEnvironment(in: repoRoot) {
            let version = pythonVersion(ofVirtualEnvironment: venv).map { " (Python \($0))" } ?? ""
            lines.append("- Python virtualenv: `\(venv.lastPathComponent)`\(version) — its `bin/` is first on PATH")
        } else {
            lines.append("- Python virtualenv: none")
        }
        appendFilesLine("Python project files", pythonFiles, in: repoRoot, to: &lines)
        if appendFilesLine("Node project files", nodeFiles, in: repoRoot, to: &lines) {
            let installed = FileManager.default.fileExists(atPath: repoRoot.appendingPathComponent("node_modules").path)
            lines.append("- node_modules: \(installed ? "installed" : "not installed")")
        }
        appendFilesLine("Swift project files", swiftFiles, in: repoRoot, to: &lines)
        let added = addedPathDirectories(repoRoot: repoRoot, inherited: inherited).map(display)
        if !added.isEmpty {
            lines.append("- PATH dirs added by the app: \(added.joined(separator: ", "))")
        }
        let folders = topLevelFolders(of: repoRoot)
        if !folders.isEmpty {
            lines.append("- Top-level folders: \(folders.joined(separator: ", "))")
        }
        lines.append("- Loop runs in an isolated worktree have no gitignored folders (.venv, node_modules).")
        return lines.joined(separator: "\n") + "\n"
    }

    /// Writes the note for the project at `projectRoot`, describing the repo
    /// the code graph uses (`RepoGraphLocator`: its `code/<repo>` child, else
    /// the root). The ONE entry point for app callers, so project open and a
    /// Loop run never overwrite each other with notes about different repos.
    @discardableResult
    public static func write(projectRoot: URL, inherited: [String: String]) -> Bool {
        let repo = RepoGraphLocator.repoToGraph(projectRoot: projectRoot) ?? projectRoot
        return write(projectRoot: projectRoot, repoRoot: repo, inherited: inherited)
    }

    /// Renders and writes the note under `projectRoot`'s `system/memory/`.
    /// Returns whether the file changed. Best-effort: a write failure returns
    /// `false` — a missing note only costs the agent a rediscovery.
    @discardableResult
    public static func write(projectRoot: URL, repoRoot: URL, inherited: [String: String]) -> Bool {
        let fm = FileManager.default
        let memoryDir = ProjectLayout(root: projectRoot).memoryDir
        let note = render(projectRoot: projectRoot, repoRoot: repoRoot, inherited: inherited)
        let url = memoryDir.appendingPathComponent(fileName)
        if let existing = try? String(contentsOf: url, encoding: .utf8), existing == note { return false }
        do {
            try fm.createDirectory(at: memoryDir, withIntermediateDirectories: true)
            try ensureIgnored(in: memoryDir)
            try note.write(to: url, atomically: true, encoding: .utf8)
            return true
        } catch {
            return false
        }
    }

    // MARK: - Pieces

    /// Makes git ignore the note: writes the folder's self-ignoring `*`
    /// marker when there is none, and appends the note's own name to a
    /// `.gitignore` that exists but covers neither.
    private static func ensureIgnored(in memoryDir: URL) throws {
        let ignore = memoryDir.appendingPathComponent(".gitignore")
        guard let existing = try? String(contentsOf: ignore, encoding: .utf8) else {
            try "*\n".write(to: ignore, atomically: true, encoding: .utf8)
            return
        }
        let entries = Set(existing.split(whereSeparator: \.isNewline)
            .map { $0.trimmingCharacters(in: .whitespaces) })
        guard !entries.contains("*"), !entries.contains(fileName) else { return }
        let separator = existing.isEmpty || existing.hasSuffix("\n") ? "" : "\n"
        try (existing + separator + fileName + "\n").write(to: ignore, atomically: true, encoding: .utf8)
    }

    @discardableResult
    private static func appendFilesLine(_ label: String, _ names: [String], in root: URL,
                                        to lines: inout [String]) -> Bool {
        let present = names.filter { FileManager.default.fileExists(atPath: root.appendingPathComponent($0).path) }
        guard !present.isEmpty else { return false }
        lines.append("- \(label): \(present.joined(separator: ", "))")
        return true
    }

    private static func relativePath(of url: URL, under root: URL) -> String {
        let base = root.standardizedFileURL.path
        let path = url.standardizedFileURL.path
        if path == base { return "." }
        return path.hasPrefix(base + "/") ? String(path.dropFirst(base.count + 1)) : url.lastPathComponent
    }

    /// `version` (venv) or `version_info` (uv) from `pyvenv.cfg`.
    private static func pythonVersion(ofVirtualEnvironment venv: URL) -> String? {
        guard let cfg = try? String(contentsOf: venv.appendingPathComponent("pyvenv.cfg"), encoding: .utf8)
        else { return nil }
        for line in cfg.split(whereSeparator: \.isNewline) {
            let parts = line.split(separator: "=", maxSplits: 1).map { $0.trimmingCharacters(in: .whitespaces) }
            if parts.count == 2, parts[0] == "version" || parts[0] == "version_info" { return parts[1] }
        }
        return nil
    }

    /// The PATH entries `ProjectRuntimeEnvironment` adds beyond `inherited`'s
    /// own, excluding the virtualenv's `bin/` (reported on its own line).
    private static func addedPathDirectories(repoRoot: URL, inherited: [String: String]) -> [String] {
        let own = Set((inherited["PATH"] ?? "").split(separator: ":").map(String.init))
        let venvBin = ProjectRuntimeEnvironment.virtualEnvironment(in: repoRoot)?
            .appendingPathComponent("bin").path
        let composed = ProjectRuntimeEnvironment.overrides(for: repoRoot, inherited: inherited)["PATH"] ?? ""
        return composed.split(separator: ":").map(String.init)
            .filter { !own.contains($0) && $0 != venvBin }
    }

    private static func topLevelFolders(of root: URL) -> [String] {
        let children = (try? FileManager.default.contentsOfDirectory(
            at: root, includingPropertiesForKeys: [.isDirectoryKey], options: [.skipsHiddenFiles])) ?? []
        return children
            .filter { (try? $0.resourceValues(forKeys: [.isDirectoryKey]))?.isDirectory == true }
            .map(\.lastPathComponent)
            .filter { !hiddenFolders.contains($0) }
            .sorted()
    }
}
