// Email note writer using unified NoteService
// Writes generated email notes to notes/emails/ instead of Email/

import Foundation
import Yams

/// Writes email notes using the unified NoteService.
/// Replaces EmailFileStore for the generated notes output.
struct EmailNoteWriter {
    let noteService: NoteService
    let repoRoot: URL

    init(repoRoot: URL) {
        self.repoRoot = repoRoot
        self.noteService = NoteService(repoRoot: repoRoot)
    }

    /// Write a generated email note to the unified notes structure.
    @discardableResult
    func writeNote(
        from: String,
        date: Date,
        subject: String,
        classification c: LlmIdeAPIClient.EmailClassification,
        originalBody: String,
        sourceHash: String,
        rawFile: String
    ) async throws -> URL {
        // Build YAML frontmatter
        var fm = """
        ---
        source: email
        platform: email
        from: \(yamlScalar(from))
        date: \(AppDateFormatter.isoString(date))
        category: \(c.category)
        noteWorthy: true
        sourceHash: \(yamlScalar(sourceHash))
        rawFile: \(rawFile)
        todos:

        """
        if c.todos.isEmpty {
            fm += "  []\n"
        }
        for t in c.todos {
            fm += "  - title: \(yamlScalar(t.title))\n"
            fm += "    detail: \(yamlScalar(t.detail))\n"
            fm += "    due: \(t.due.map { "\"\($0)\"" } ?? "null")\n"
            fm += "    priority: \(t.priority)\n"
            fm += "    issue: null\n"
        }
        fm += "---\n\n"

        // Build markdown body
        var md = fm
        md += "# \(subject.isEmpty ? "Email" : subject)\n\n"
        md += "**Summary:** \(c.summary)\n\n"
        md += "## To-dos\n\n"
        if c.todos.isEmpty {
            md += "_No action items._\n\n"
        } else {
            for t in c.todos {
                let due = t.due.map { " — due \($0)" } ?? ""
                md += "- [ ] \(t.title)\(due) (\(t.priority))\n"
            }
            md += "\n"
        }
        md += "## Original\n\n\(originalBody)"

        // Generate filename
        let filename = Self.filename(date: date, subject: subject)

        // Create note metadata
        let metadata = NoteMetadata(
            id: "", // Will be generated by NoteService
            type: .email,
            source: "email",
            title: subject.isEmpty ? "Email" : subject,
            date: AppDateFormatter.isoString(date),
            path: "",
            rawFile: rawFile,
            sourceHash: sourceHash,
            generatedAt: AppDateFormatter.isoString(Date()),
            tags: [c.category],
            participants: nil,
            fileSize: 0
        )

        // Save via NoteService
        let saved = try await noteService.saveNote(
            type: .email,
            filename: filename,
            content: Data(md.utf8),
            metadata: metadata
        )

        // Return full file URL
        return repoRoot.appendingPathComponent(saved.path)
    }

    /// Write a skipped email stub.
    @discardableResult
    func writeSkipped(
        from: String,
        date: Date,
        subject: String,
        category: String,
        originalBody: String,
        sourceHash: String,
        rawFile: String
    ) async throws -> URL {
        let md = """
        ---
        source: email
        platform: email
        from: \(yamlScalar(from))
        date: \(AppDateFormatter.isoString(date))
        category: \(category)
        noteWorthy: false
        sourceHash: \(yamlScalar(sourceHash))
        rawFile: \(rawFile)
        skipped: \(category)
        ---

        # \(subject.isEmpty ? "Email" : subject)

        ## Original

        \(originalBody)
        """

        let filename = Self.filename(date: date, subject: subject)

        let metadata = NoteMetadata(
            id: "",
            type: .email,
            source: "email",
            title: subject.isEmpty ? "Email" : subject,
            date: AppDateFormatter.isoString(date),
            path: "",
            rawFile: rawFile,
            sourceHash: sourceHash,
            generatedAt: AppDateFormatter.isoString(Date()),
            tags: [category],
            participants: nil,
            fileSize: 0
        )

        let saved = try await noteService.saveNote(
            type: .email,
            filename: filename,
            content: Data(md.utf8),
            metadata: metadata
        )

        return repoRoot.appendingPathComponent(saved.path)
    }

    /// Scan existing notes and collect source hashes.
    /// Used for deduplication in the generation pipeline.
    func existingSourceHashes() async throws -> Set<String> {
        let notes = try await noteService.queryNotes(NoteFilter(type: .email))
        var hashes: Set<String> = []
        for note in notes {
            if let hash = note.sourceHash {
                hashes.insert(hash)
            }
        }
        return hashes
    }

    // MARK: - Helpers

    private static func filename(date: Date, subject: String) -> String {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM-dd-HHmmss"
        f.timeZone = TimeZone(identifier: "UTC")
        let stamp = f.string(from: date)
        let slug = slugify(subject.isEmpty ? "email" : subject)
        return "\(stamp)-\(slug).md"
    }

    private static func slugify(_ s: String) -> String {
        let allowed = CharacterSet.alphanumerics
        let cleaned = s.lowercased().unicodeScalars.map { allowed.contains($0) ? Character($0) : "-" }
        let joined = String(cleaned)
        let collapsed = joined.split(separator: "-").joined(separator: "-")
        return String(collapsed.prefix(60)).isEmpty ? "email" : String(collapsed.prefix(60))
    }

    /// Quote a YAML scalar so ':' / '@' / quotes in addresses & titles stay valid.
    private func yamlScalar(_ s: String) -> String {
        "\"" + s.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"") + "\""
    }
}
