import Testing
import Foundation
@testable import MeetNotesMac

struct MemoryNotesWriterTests {
    private func sample() -> CGData {
        let mod = CGNode(id: "m1", title: "Auth", kind: .module)
        let file = CGNode(id: "f1", title: "AuthService.swift",
                          kind: .file, metadata: ["path": "Sources/Auth/AuthService.swift"])
        let sym = CGNode(id: "s1", title: "AuthService.login",
                         kind: .symbol,
                         metadata: ["file": "Sources/Auth/AuthService.swift",
                                    "symbolKind": "func"])
        let doc = CGNode(id: "d1", title: "Auth design",
                         kind: .docPage, metadata: ["path": "docs/auth.md"])
        let chunk = CGNode(id: "c1", title: "JWT rotation",
                           kind: .noteFact, metadata: ["tags": "auth, jwt"])
        let nodes = [mod, file, sym, doc, chunk]
        let edges = [
            CGEdge(fromId: "m1", toId: "f1", kind: .defines),
            CGEdge(fromId: "f1", toId: "s1", kind: .defines),
            CGEdge(fromId: "d1", toId: "c1", kind: .defines),
            CGEdge(fromId: "d1", toId: "s1", kind: .references)
        ]
        return CGData(nodes: nodes, edges: edges)
    }

    @Test func renderIncludesStatsAndAllMajorSections() {
        let md = MemoryNotesWriter.render(sample(),
                                          generatedAt: Date(timeIntervalSince1970: 1_716_465_600))
        #expect(md.hasPrefix("# Graph notes"))
        #expect(md.contains("Auto-generated by Understand-Anything on 2024-05-23T12:00:00Z"))
        #expect(md.contains("## Stats"))
        #expect(md.contains("**1** files"))
        #expect(md.contains("**1** symbols"))
        #expect(md.contains("## Modules"))
        #expect(md.contains("### Auth"))
        #expect(md.contains("## Files (top by symbol count)"))
        #expect(md.contains("`AuthService.login`"))
        #expect(md.contains("## Docs"))
        #expect(md.contains("### Auth design"))
        #expect(md.contains("JWT rotation"))
        #expect(md.contains("auth, jwt"))
        #expect(md.contains("## Cross-references"))
        #expect(md.contains("→ references"))
    }

    @Test func writeCreatesFileUnderUnderstandAnythingMemory() throws {
        let repo = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("graph-notes-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: repo, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: repo) }

        let url = try MemoryNotesWriter.write(sample(), at: repo)
        #expect(url.path.hasSuffix(".understand-anything/memory/graph-notes.md"))
        #expect(FileManager.default.fileExists(atPath: url.path))
        let body = try String(contentsOf: url, encoding: .utf8)
        #expect(body.contains("# Graph notes"))
    }

    @Test func emptyGraphProducesValidMarkdown() {
        let md = MemoryNotesWriter.render(CGData.empty)
        #expect(md.hasPrefix("# Graph notes"))
        #expect(md.contains("**0** files"))
        // Sections with no content should not appear at all.
        #expect(!md.contains("## Modules"))
        #expect(!md.contains("## Docs"))
        #expect(!md.contains("## Cross-references"))
    }
}
