// After every `understand-anything analyze`, render the parsed CGData as a
// human-readable markdown brief and drop it at
// `<repo>/.understand-anything/memory/graph-notes.md`.
//
// This file is the agent's "cheatsheet" — what modules exist, which
// symbols live where, what docs we have, and how they cross-link.
// The format mirrors the InfiniteBrain note style (sections with
// stats + bulleted indexes) so the agent's installed skill can read
// it without bespoke parsing.
//
// graph-notes.md is REGENERATED on every update — never preserve
// edits. User-curated facts go in repo.md (untouched by this
// writer) so a graph rebuild can't clobber them.

import Foundation

public enum MemoryNotesWriter {

    /// Render + write. Overwrites any existing file. Best-effort —
    /// any I/O error is bubbled up so the caller can decide whether
    /// it's worth surfacing (understand-anything analyze succeeded even if this
    /// file didn't land).
    @discardableResult
    public static func write(_ data: CGData,
                             at repoRoot: URL,
                             generatedAt: Date = Date()) throws -> URL {
        let memDir = repoRoot
            .appendingPathComponent(".understand-anything", isDirectory: true)
            .appendingPathComponent("memory", isDirectory: true)
        try FileManager.default.createDirectory(at: memDir, withIntermediateDirectories: true)
        let url = memDir.appendingPathComponent("graph-notes.md")
        let body = render(data, generatedAt: generatedAt)
        try body.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    /// Pure rendering — exposed for tests + callers that want the
    /// markdown without touching the filesystem.
    public static func render(_ data: CGData, generatedAt: Date = Date()) -> String {
        let stamp = generatedAt.iso8601String
        var out = """
        # Graph notes

        > Auto-generated by Understand-Anything on \(stamp). This file is rewritten on every
        > `understand-anything analyze` — for curated facts the agent should remember, edit
        > `repo.md` instead.

        """

        out += "\n"
        out += stats(data)
        out += sectionJoin(modulesSection(data))
        out += sectionJoin(filesSection(data))
        out += sectionJoin(docsSection(data))
        out += sectionJoin(crossRefSection(data))
        return out
    }

    /// Empty sections produce empty strings; we only want a blank line
    /// before non-empty ones so the file doesn't end up double-spaced
    /// or, worse, with a hollow trailing newline tower.
    private static func sectionJoin(_ s: String) -> String {
        s.isEmpty ? "" : "\n\n" + s
    }

    // MARK: - Sections

    private static func stats(_ data: CGData) -> String {
        let files = data.nodes.filter { $0.kind == .file }.count
        let symbols = data.nodes.filter { $0.kind == .symbol }.count
        let modules = data.nodes.filter { $0.kind == .module }.count
        let docs = data.nodes.filter { $0.kind == .docPage || $0.kind == .memoryDoc }.count
        let chunks = data.nodes.filter { $0.kind == .memoryChunk
            || CGNodeKind.atomicNoteKinds.contains($0.kind) }.count
        return """
        ## Stats

        - **\(files)** files · **\(symbols)** symbols · **\(modules)** modules
        - **\(docs)** docs · **\(chunks)** chunks
        - **\(data.edges.count)** edges
        """
    }

    private static func modulesSection(_ data: CGData) -> String {
        let modules = data.nodes.filter { $0.kind == .module }
            .sorted { $0.title.lowercased() < $1.title.lowercased() }
        guard !modules.isEmpty else { return "" }
        var out = "## Modules\n"
        for m in modules {
            let kids = childSymbols(of: m, in: data).prefix(maxItemsPerGroup)
            out += "\n### \(m.title)\n"
            if kids.isEmpty {
                out += "- _(no symbols indexed)_\n"
            } else {
                for k in kids {
                    out += "- `\(k.title)`"
                    if let path = k.metadata["file"] ?? k.metadata["path"] {
                        out += " — `\(path)`"
                    }
                    out += "\n"
                }
                if childSymbols(of: m, in: data).count > maxItemsPerGroup {
                    out += "- _… and \(childSymbols(of: m, in: data).count - maxItemsPerGroup) more_\n"
                }
            }
        }
        return out
    }

    private static func filesSection(_ data: CGData) -> String {
        // Top files by *real* symbol count. Skip files that understand-anything
        // indexed only as a single "<filename> script" pseudo-symbol
        // (build.sh, etc) — those tell the agent nothing structural.
        let files = data.nodes.filter { $0.kind == .file && hasCodeExtension($0) }
        guard !files.isEmpty else { return "" }
        let ranked = files
            .map { ($0, realSymbols(of: $0, in: data)) }
            .filter { !$0.1.isEmpty }
            .sorted { $0.1.count > $1.1.count }
            .prefix(maxFilesShown)
        guard !ranked.isEmpty else { return "" }
        var out = "## Files (top by symbol count)\n"
        for (f, kids) in ranked {
            let path = f.metadata["path"] ?? f.title
            out += "\n### `\(path)`\n"
            for k in kids.prefix(maxItemsPerGroup) {
                let kind = k.metadata["symbolKind"] ?? k.kind.displayName.lowercased()
                out += "- `\(k.title)` _(\(kind))_\n"
            }
            if kids.count > maxItemsPerGroup {
                out += "- _… and \(kids.count - maxItemsPerGroup) more_\n"
            }
        }
        return out
    }

    /// Symbols under `file` that aren't just "<name> script"
    /// placeholders understand-anything emits for shell scripts and similar.
    private static func realSymbols(of file: CGNode, in data: CGData) -> [CGNode] {
        let placeholder = "\(file.title) script"
        return childSymbols(of: file, in: data)
            .filter { $0.title != placeholder }
    }

    private static func hasCodeExtension(_ n: CGNode) -> Bool {
        let path = n.metadata["path"] ?? n.title
        let codeExtensions: Set<String> = [
            "swift", "ts", "tsx", "js", "jsx", "py", "rb", "go", "rs",
            "java", "kt", "c", "cc", "cpp", "h", "hpp", "m", "mm",
            "cs", "scala", "clj", "ex", "exs", "lua", "php"
        ]
        let ext = (path as NSString).pathExtension.lowercased()
        return codeExtensions.contains(ext)
    }

    private static func docsSection(_ data: CGData) -> String {
        // Real doc roots only: must be docPage/memoryDoc AND must
        // either have child chunks OR carry a `path` metadata field.
        // This filters out heading-level pseudo-docs that understand-anything
        // emits for every "## heading" in a markdown file.
        let raw = data.nodes.filter { $0.kind == .docPage || $0.kind == .memoryDoc }
        var seenPaths = Set<String>()
        var seenTitles = Set<String>()
        var docs: [CGNode] = []
        for d in raw {
            // Skip pseudo-doc titles like "1.1 Foo", "2 — Bar".
            if looksLikeHeadingTitle(d.title) { continue }
            // Dedupe by path first (canonical), then by title.
            if let path = d.metadata["path"] {
                if seenPaths.contains(path) { continue }
                seenPaths.insert(path)
            } else if seenTitles.contains(d.title) {
                continue
            } else {
                seenTitles.insert(d.title)
            }
            // Demand evidence this is a real doc — has chunks or a path.
            if d.metadata["path"] == nil && childChunks(of: d, in: data).isEmpty {
                continue
            }
            docs.append(d)
        }
        guard !docs.isEmpty else { return "" }
        docs.sort { $0.title.lowercased() < $1.title.lowercased() }
        var out = "## Docs\n"
        for d in docs.prefix(maxDocsShown) {
            out += "\n### \(d.title)\n"
            if let path = d.metadata["path"] {
                out += "_from_ `\(path)`\n"
            }
            let chunks = childChunks(of: d, in: data)
                .filter { !looksLikeHeadingTitle($0.title) || !$0.title.trimmingCharacters(in: .whitespaces).isEmpty }
            for c in chunks.prefix(maxItemsPerGroup) {
                out += "- \(c.title)"
                if let tags = c.metadata["tags"], !tags.isEmpty {
                    out += " — _tags: \(tags)_"
                }
                out += "\n"
            }
            if chunks.count > maxItemsPerGroup {
                out += "- _… and \(chunks.count - maxItemsPerGroup) more chunks_\n"
            }
        }
        if docs.count > maxDocsShown {
            out += "\n_… and \(docs.count - maxDocsShown) more docs._\n"
        }
        return out
    }

    /// Understand-Anything sometimes promotes every markdown heading to a docPage
    /// node. Their titles tend to be `1.2 Foo`, `2 — Bar`, etc.
    /// Filter them out of the top-level doc index — they belong as
    /// chunks under their parent doc, not as docs themselves.
    private static func looksLikeHeadingTitle(_ s: String) -> Bool {
        let t = s.trimmingCharacters(in: .whitespaces)
        guard let first = t.first, first.isNumber else { return false }
        // Patterns: "1 foo", "1.2 foo", "1 — foo", "1) foo"
        let head = t.prefix { $0.isNumber || $0 == "." }
        guard !head.isEmpty else { return false }
        let rest = t.dropFirst(head.count).first
        return rest == " " || rest == ")" || rest == "—" || rest == "-"
    }

    private static func crossRefSection(_ data: CGData) -> String {
        // Top doc→code references — the cross-cutting links that
        // make the graph valuable. We aggressively dedupe and drop
        // test-helper noise so the agent sees architecture, not the
        // call-graph of every assertion.
        let nodesByID = Dictionary(uniqueKeysWithValues: data.nodes.map { ($0.id, $0) })
        let candidates = data.edges.compactMap { e -> (CGNode, CGNode, CGEdgeKind)? in
            guard e.kind == .references || e.kind == .calls || e.kind == .imports else { return nil }
            guard let from = nodesByID[e.fromId], let to = nodesByID[e.toId] else { return nil }
            if isNoiseRef(from: from, to: to) { return nil }
            return (from, to, e.kind)
        }
        // Dedupe by (from.title, to.title, kind) — understand-anything emits one
        // edge per call-site, which floods the list with duplicates.
        var seen = Set<String>()
        var unique: [(CGNode, CGNode, CGEdgeKind)] = []
        for tup in candidates {
            let key = "\(tup.0.title)::\(tup.1.title)::\(tup.2.rawValue)"
            if seen.contains(key) { continue }
            seen.insert(key)
            unique.append(tup)
        }
        guard !unique.isEmpty else { return "" }
        var out = "## Cross-references\n\n"
        for (from, to, kind) in unique.prefix(maxCrossRefs) {
            let verb: String
            switch kind {
            case .references:       verb = "→ references"
            case .calls:            verb = "→ calls"
            case .imports:          verb = "→ imports"
            case .defines:          verb = "→ defines"
            case .relatedTo:        verb = "→ related to"
            // Structural
            case .exports:          verb = "→ exports"
            case .contains:         verb = "→ contains"
            case .inherits:         verb = "→ inherits"
            case .implements:       verb = "→ implements"
            // Behavioral
            case .subscribes:       verb = "→ subscribes"
            case .publishes:        verb = "→ publishes"
            case .middleware:       verb = "→ middleware"
            // Data flow
            case .readsFrom:        verb = "→ reads from"
            case .writesTo:         verb = "→ writes to"
            case .transforms:       verb = "→ transforms"
            case .validates:        verb = "→ validates"
            // Dependencies
            case .dependsOn:        verb = "→ depends on"
            case .testedBy:         verb = "→ tested by"
            case .configures:       verb = "→ configures"
            // Semantic
            case .similarTo:        verb = "→ similar to"
            // Infrastructure
            case .deploys:          verb = "→ deploys"
            case .serves:           verb = "→ serves"
            case .provisions:       verb = "→ provisions"
            case .triggers:         verb = "→ triggers"
            // Schema
            case .migrates:         verb = "→ migrates"
            case .documents:        verb = "→ documents"
            case .routes:           verb = "→ routes"
            case .definesSchema:    verb = "→ defines schema"
            // Domain
            case .containsFlow:     verb = "→ contains flow"
            case .flowStep:         verb = "→ flow step"
            case .crossDomain:      verb = "→ cross-domain"
            // Knowledge
            case .cites:            verb = "→ cites"
            case .contradicts:      verb = "→ contradicts"
            case .buildsOn:         verb = "→ builds on"
            case .exemplifies:      verb = "→ exemplifies"
            case .categorizedUnder: verb = "→ categorized under"
            case .authoredBy:       verb = "→ authored by"
            }
            out += "- `\(from.title)` \(verb) `\(to.title)`\n"
        }
        if unique.count > maxCrossRefs {
            out += "- _… and \(unique.count - maxCrossRefs) more references_\n"
        }
        return out
    }

    /// Drop cross-refs that don't tell the agent anything useful:
    /// — test methods as source (`.fooTest()` calls X)
    /// — bare-dot helpers as source (`.init()`, `.write()`)
    /// — protocol-conformance noise (every View → View, every Codable
    ///   → Codable). The framework protocols are documented elsewhere;
    ///   listing every conformer adds nothing.
    private static func isNoiseRef(from: CGNode, to: CGNode) -> Bool {
        if isTestNode(from) { return true }
        if isBareDotMethod(from.title) { return true }
        if Self.protocolNoiseTargets.contains(to.title) { return true }
        return false
    }

    /// Targets where a high-fanin edge is structural noise — every
    /// SwiftUI view references `View`, every codable references
    /// `Codable`, etc. Filtering these is what turns the file from
    /// "list of conformances" into "list of architecture".
    private static let protocolNoiseTargets: Set<String> = [
        "View", "App", "Scene", "ViewModifier", "Shape", "Animatable",
        "Codable", "Encodable", "Decodable",
        "Identifiable", "Hashable", "Equatable", "Comparable",
        "Sendable", "AnyObject", "Error", "LocalizedError",
        "ObservableObject", "DynamicProperty", "EnvironmentKey",
        "CaseIterable", "RawRepresentable",
        // Raw-value primitives: `enum Foo: String` is convention,
        // not architecture.
        "String", "Int", "Bool", "Double", "Float", "UInt"
    ]

    private static func isTestNode(_ n: CGNode) -> Bool {
        let t = n.title
        if t.contains("Tests") { return true }
        // Bare `<lowerCamel>()` (with or without leading dot) is
        // almost always a Swift Testing @Test method when the name
        // contains no further `.` qualifier.
        guard t.hasSuffix("()") else { return false }
        let inner = t.hasPrefix(".") ? String(t.dropFirst().dropLast(2)) : String(t.dropLast(2))
        guard !inner.isEmpty, !inner.contains("."), let first = inner.first,
              first.isLowercase else { return false }
        return true
    }

    private static func isBareDotMethod(_ title: String) -> Bool {
        // `.init()`, `.write()`, `.makeRow()` — verbs without a
        // receiver. Useful in tests, noise in an architectural index.
        guard title.hasPrefix(".") && title.hasSuffix("()") else { return false }
        let inner = title.dropFirst().dropLast(2)
        return !inner.contains(".")
    }

    // MARK: - Helpers

    private static func childSymbols(of parent: CGNode, in data: CGData) -> [CGNode] {
        let nodes = Dictionary(uniqueKeysWithValues: data.nodes.map { ($0.id, $0) })
        return data.edges
            .filter { $0.fromId == parent.id && $0.kind == .defines }
            .compactMap { nodes[$0.toId] }
            .filter { $0.kind == .symbol }
            .sorted { $0.title.lowercased() < $1.title.lowercased() }
    }

    private static func childChunks(of parent: CGNode, in data: CGData) -> [CGNode] {
        let nodes = Dictionary(uniqueKeysWithValues: data.nodes.map { ($0.id, $0) })
        return data.edges
            .filter { $0.fromId == parent.id }
            .compactMap { nodes[$0.toId] }
            .filter { $0.kind == .memoryChunk || CGNodeKind.atomicNoteKinds.contains($0.kind) }
            .sorted { $0.title.lowercased() < $1.title.lowercased() }
    }

    // MARK: - Limits

    /// Caps chosen so a ~1k-node graph still fits in a single agent
    /// prompt comfortably. Bump if the agent context expands.
    private static let maxItemsPerGroup = 20
    private static let maxFilesShown = 30
    private static let maxDocsShown = 40
    private static let maxCrossRefs = 60
}
