// Phase 5 — task orchestrator.  Takes a plan (already saved to KB) and
// pushes each task as a ticket in an external system.  Three modes:
//
//   target='preview'  — never call any external API; return the exact
//                       payload that WOULD be sent.  Default.
//   target='github'   — create one Issue per task in the named repo.
//   target='backlog'  — create one Issue per task in a Backlog space.
//
// Tasks already dispatched (meta.dispatched.url present) are SKIPPED so
// re-running the dispatch is idempotent — handy when only a subset
// failed on the first attempt.

import { getPlan, mergeTaskMeta, getTaskById } from '../kb/db.mjs';
import { pMap } from '../core/p-map.mjs';
import { SECRET_PATTERNS } from '../guardrails/rules.mjs';
import { jittered } from './runtime.mjs';
import { logger } from '../core/logger.mjs';

const log = logger.child({ component: 'dispatcher' });

// Strip API keys / tokens from external-API error bodies before surfacing
// them in the response — provider APIs occasionally echo credentials back
// in 4xx messages (e.g. "Bad credentials for ghp_abc…").
function redactErrorBody(text) {
  let out = String(text || '');
  for (const { re } of SECRET_PATTERNS) {
    out = out.replace(new RegExp(re.source, re.flags.replace('g', '') + 'g'), '[redacted]');
  }
  return out.slice(0, 300);
}

const ALLOWED_TARGETS = new Set(['preview', 'github', 'backlog', 'linear']);

// Backlog spaces are subdomains like "yourteam.backlog.com" or
// "yourteam.backlog.jp".  Interpolating an unvalidated `space` into a
// URL allows an attacker (or a malformed config) to redirect requests
// elsewhere — including the apiKey in the query string — by passing
// e.g. "evil.com" or "evil.com#" or "evil.com/path".  We validate
// strictly: lowercase DNS labels, one of the known Backlog TLDs.
const BACKLOG_TLD_RE = /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.backlog\.(?:com|jp|tool)$/;
function assertBacklogSpace(space) {
  if (typeof space !== 'string' || !BACKLOG_TLD_RE.test(space)) {
    throw new Error('Backlog space must be a "<subdomain>.backlog.{com,jp,tool}" hostname');
  }
}

function buildBody(plan, task) {
  // Markdown body shared across providers.  Keep machine-readable so
  // the loopback (Phase 8 outcome watcher) can re-link a ticket back to
  // its plan + task without grepping titles.
  const lines = [
    `**Plan:** ${plan.title} (${plan.id})`,
    `**Task ID:** ${task.id}`,
  ];
  if (task.milestone) lines.push(`**Milestone:** ${task.milestone}`);
  if (task.owner)     lines.push(`**Owner:** ${task.owner}`);
  if (task.due)       lines.push(`**Due:** ${task.due}`);
  if (task.estimateDays != null) lines.push(`**Estimate:** ${task.estimateDays}d`);
  if (task.risk)      lines.push(`**Risk:** ${task.risk}${task.riskReason ? ` — ${task.riskReason}` : ''}`);
  if (task.description) lines.push('', task.description);
  if (Array.isArray(task.files) && task.files.length > 0) {
    lines.push('', '**Code refs:**');
    for (const f of task.files.slice(0, 10)) lines.push(`- \`${f.title}\` (${f.ref})`);
  }
  lines.push('', '_Generated by LLM IDE — autonomous project system._');
  return lines.join('\n');
}

function shouldSkip(task) {
  return Boolean(task.meta?.dispatched?.url);
}

// --- GitHub adapter -------------------------------------------------------

async function dispatchGithub(userId, { plan, tasks, repo, token, labels = [] }) {
  if (!repo || !/^[^/]+\/[^/]+$/.test(repo)) {
    throw new Error('GitHub repo must be "owner/name"');
  }
  if (!token) {
    throw new Error('GitHub token required to create issues');
  }
  const url = `https://api.github.com/repos/${repo}/issues`;
  const headers = {
    'Accept': 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Authorization': `Bearer ${token}`,
    'Content-Type': 'application/json',
    'User-Agent': 'llm-ide-extension',
  };

  return pMap(tasks, async (task) => {
    if (shouldSkip(task)) {
      return { taskId: task.id, status: 'skipped', reason: 'already dispatched' };
    }
    const body = JSON.stringify({
      title: task.title.slice(0, 250),
      body: buildBody(plan, task),
      labels: [...labels, ...(task.risk ? [`risk:${task.risk}`] : [])].slice(0, 10),
      assignees: task.owner ? [task.owner] : undefined,
    });
    const r = await fetch(url, { method: 'POST', headers, body, signal: AbortSignal.timeout(15_000) });
    if (!r.ok) {
      const err = redactErrorBody(await r.text());
      return { taskId: task.id, status: 'error', code: r.status, error: err };
    }
    const issue = await r.json();
    const dispatched = {
      provider: 'github',
      url: issue.html_url,
      number: issue.number,
      state: issue.state,
      dispatchedAt: new Date().toISOString(),
    };
    mergeTaskMeta(userId, task.id, { dispatched });
    return { taskId: task.id, status: 'ok', ...dispatched };
  });
}

// --- Backlog adapter ------------------------------------------------------

// Backlog is the most common tracker for Japanese teams (and the user's
// company appears to be Japan-based).  API shape is form-encoded rather
// than JSON; we encode the title + description and rely on the API key
// being passed as a query parameter.
async function dispatchBacklog(userId, { plan, tasks, space, projectId, apiKey, issueTypeId, priorityId = 3 }) {
  if (!space || !projectId || !apiKey || !issueTypeId) {
    throw new Error('Backlog requires space, projectId, apiKey, and issueTypeId');
  }
  assertBacklogSpace(space);
  // Backlog v2 API requires the API key as a *form body* parameter when
  // using POST — the URL-query variant works too but ends up in web-server
  // access logs and proxy logs.  By putting apiKey in the POST body
  // (alongside the other form fields) we keep it out of the URL line
  // without breaking the API.  Bearer-header auth is not available for
  // Personal API keys in Backlog; OAuth 2 would be the alternative, but
  // that requires a redirect flow incompatible with a desktop extension.
  const url = `https://${space}/api/v2/issues`;
  const headers = {
    'Content-Type': 'application/x-www-form-urlencoded',
    'User-Agent': 'llm-ide-extension',
  };

  return pMap(tasks, async (task) => {
    if (shouldSkip(task)) {
      return { taskId: task.id, status: 'skipped', reason: 'already dispatched' };
    }
    const params = new URLSearchParams();
    params.set('apiKey', apiKey);             // in body, not URL
    params.set('projectId', String(projectId));
    params.set('summary', task.title.slice(0, 250));
    params.set('description', buildBody(plan, task));
    params.set('issueTypeId', String(issueTypeId));
    params.set('priorityId', String(priorityId));
    if (task.due && /^\d{4}-\d{2}-\d{2}$/.test(task.due)) params.set('dueDate', task.due);
    const r = await fetch(url, { method: 'POST', headers, body: params.toString(), signal: AbortSignal.timeout(15_000) });
    if (!r.ok) {
      const err = redactErrorBody(await r.text());
      return { taskId: task.id, status: 'error', code: r.status, error: err };
    }
    const issue = await r.json();
    const dispatched = {
      provider: 'backlog',
      url: `https://${space}/view/${encodeURIComponent(issue.issueKey)}`,
      number: issue.issueKey,
      state: 'open',
      dispatchedAt: new Date().toISOString(),
    };
    mergeTaskMeta(userId, task.id, { dispatched });
    return { taskId: task.id, status: 'ok', ...dispatched };
  });
}

// --- Linear adapter -------------------------------------------------------
// Linear's API is GraphQL.  Authentication: a personal API key passed in
// the `Authorization` header (no "Bearer " prefix).  We mutate one issue
// per task; assignment is done by display name → user-id lookup which we
// skip in Phase 7 (assignees can be added via Linear's UI after creation).

async function dispatchLinear(userId, { plan, tasks, teamId, apiKey, projectId }) {
  if (!teamId || !apiKey) {
    throw new Error('Linear requires teamId and apiKey');
  }
  const endpoint = 'https://api.linear.app/graphql';
  const headers = {
    'Authorization': apiKey,
    'Content-Type': 'application/json',
    'User-Agent': 'llm-ide-extension',
  };
  const mutation = `
    mutation($input: IssueCreateInput!) {
      issueCreate(input: $input) {
        success
        issue { id identifier url state { name } }
      }
    }
  `;

  return pMap(tasks, async (task) => {
    if (shouldSkip(task)) {
      return { taskId: task.id, status: 'skipped', reason: 'already dispatched' };
    }
    const input = {
      teamId,
      title: task.title.slice(0, 250),
      description: buildBody(plan, task),
    };
    if (projectId) input.projectId = projectId;
    if (task.due && /^\d{4}-\d{2}-\d{2}$/.test(task.due)) input.dueDate = task.due;
    if (task.estimateDays != null) input.estimate = Math.round(task.estimateDays);

    const r = await fetch(endpoint, {
      method: 'POST', headers,
      body: JSON.stringify({ query: mutation, variables: { input } }),
      signal: AbortSignal.timeout(15_000),
    });
    if (!r.ok) {
      const err = redactErrorBody(await r.text());
      return { taskId: task.id, status: 'error', code: r.status, error: err };
    }
    const data = await r.json();
    if (data?.errors?.length) {
      return {
        taskId: task.id, status: 'error', code: 200,
        error: data.errors.map((e) => e.message).join('; ').slice(0, 300),
      };
    }
    const issue = data?.data?.issueCreate?.issue;
    if (!issue) {
      return { taskId: task.id, status: 'error', error: 'No issue returned by Linear' };
    }
    const dispatched = {
      provider: 'linear',
      url: issue.url,
      number: issue.identifier,
      state: issue.state?.name || 'open',
      dispatchedAt: new Date().toISOString(),
    };
    mergeTaskMeta(userId, task.id, { dispatched });
    return { taskId: task.id, status: 'ok', ...dispatched };
  });
}

// --- Preview adapter ------------------------------------------------------

function dispatchPreview({ plan, tasks }) {
  return tasks.map((task) => ({
    taskId: task.id,
    status: 'preview',
    title: task.title.slice(0, 250),
    body:  buildBody(plan, task),
    labels: task.risk ? [`risk:${task.risk}`] : [],
    assignees: task.owner ? [task.owner] : [],
  }));
}

// --- Retry helpers --------------------------------------------------------
//
// When a dispatch attempt fails (HTTP error, timeout, bad config) we
// record retry state in task meta so the background poller (or the user
// via "Retry failed" in the UI) can re-attempt with exponential backoff.
//
// meta.dispatchRetry = { attempts, nextRetryAt, lastError, target }
//
// Back-off schedule (per attempt count):
//   1 → 1 min, 2 → 5 min, 3 → 15 min, 4 → 1 hr, 5+ → 4 hr

const RETRY_DELAYS_MS = [
  60_000,            // attempt 1 → retry after 1 min
  5 * 60_000,        // attempt 2 → 5 min
  15 * 60_000,       // attempt 3 → 15 min
  60 * 60_000,       // attempt 4 → 1 hr
  4 * 60 * 60_000,   // attempt 5+ → 4 hr (max)
];
const MAX_RETRY_ATTEMPTS = 5;

// Cap on how many tasks may be retried concurrently in a single
// retryFailedDispatches() sweep.  Without a limit a large backlog of
// failed tasks could spawn hundreds of simultaneous outbound HTTP
// requests, exhausting file descriptors and hammering provider APIs.
const MAX_CONCURRENT_RETRIES = 5;

// Absolute wall-clock cap on one retryFailedDispatches() sweep.
const RETRY_SWEEP_DEADLINE_MS = 120_000;


// Read the existing retry count from the DB so we advance the backoff
// correctly even when the caller doesn't know the current attempt number.
// This is important: every code path (first dispatch, server-side retry,
// manual retry) calls this function without tracking attempt state itself.
function recordDispatchRetry(userId, taskId, target, error) {
  const existing = getTaskById(userId, taskId);
  const prevAttempts = existing?.meta?.dispatchRetry?.attempts || 0;
  const attempts = prevAttempts + 1;
  if (attempts > MAX_RETRY_ATTEMPTS) {
    // Cap reached — leave the existing retry record intact so the UI
    // can surface "gave up after N attempts" rather than clearing it.
    mergeTaskMeta(userId, taskId, {
      dispatchRetry: {
        ...(existing?.meta?.dispatchRetry || {}),
        gaveUp: true,
        lastError: String(error).slice(0, 300),
        target,
      },
    });
    return;
  }
  const baseMs = RETRY_DELAYS_MS[Math.min(attempts - 1, RETRY_DELAYS_MS.length - 1)];
  const nextRetryAt = new Date(Date.now() + jittered(baseMs)).toISOString();
  mergeTaskMeta(userId, taskId, {
    dispatchRetry: { attempts, nextRetryAt, lastError: String(error).slice(0, 300), target, gaveUp: false },
  });
}

function clearDispatchRetry(userId, taskId) {
  mergeTaskMeta(userId, taskId, { dispatchRetry: null });
}

// Amend each adapter result to record retry metadata on failure.
// No longer needs prevAttempts — recordDispatchRetry reads the DB itself.
function withRetryTracking(userId, target, results) {
  return results.map((r) => {
    if (r.status === 'error') {
      recordDispatchRetry(userId, r.taskId, target, r.error || 'dispatch error');
    } else if (r.status === 'ok') {
      clearDispatchRetry(userId, r.taskId);
    }
    return r;
  });
}

// Retry all failed dispatches for a user whose nextRetryAt has elapsed.
// Returns { retried: N, ok: N, failed: N }.
export async function retryFailedDispatches(userId, config = {}) {
  const { listDispatchedTasksForRetry } = await import('../kb/outcomes.mjs');
  const tasks = listDispatchedTasksForRetry(userId);
  const now = Date.now();
  const due = tasks.filter((t) => {
    const retry = t.meta?.dispatchRetry;
    if (!retry || !retry.nextRetryAt) return false;
    return new Date(retry.nextRetryAt).getTime() <= now;
  });

  let ok = 0, failed = 0, deferred = 0;

  // Process retries in batches of MAX_CONCURRENT_RETRIES to avoid
  // spawning an unbounded number of simultaneous outbound HTTP requests.
  async function retryOne(t) {
    const target = t.meta?.dispatchRetry?.target;
    if (!target || !ALLOWED_TARGETS.has(target) || target === 'preview') return;
    const plan = getPlan(userId, t.planId);
    if (!plan) return;
    const task = plan.tasks.find((pt) => pt.id === t.id);
    if (!task) return;
    try {
      let results;
      if (target === 'github')  results = await dispatchGithub(userId, { plan, tasks: [task], ...config });
      if (target === 'backlog') results = await dispatchBacklog(userId, { plan, tasks: [task], ...config });
      if (target === 'linear')  results = await dispatchLinear(userId, { plan, tasks: [task], ...config });
      if (!results) return;
      const r = results[0];
      if (r?.status === 'ok') {
        clearDispatchRetry(userId, task.id);
        ok += 1;
      } else {
        // recordDispatchRetry reads the existing attempt count from DB itself
        recordDispatchRetry(userId, task.id, target, r?.error || 'retry failed');
        failed += 1;
      }
    } catch (err) {
      recordDispatchRetry(userId, task.id, target, err.message);
      failed += 1;
    }
  }

  // Enforce MAX_CONCURRENT_RETRIES: slice `due` into batches and await
  // each batch before starting the next.  The sweep also has an
  // absolute wall-clock deadline — with a large failed backlog and a
  // slow provider, batch × 15 s timeouts could otherwise hold this
  // request open for minutes. Tasks not reached stay due and are
  // picked up by the next sweep.
  const sweepDeadline = Date.now() + RETRY_SWEEP_DEADLINE_MS;
  for (let i = 0; i < due.length; i += MAX_CONCURRENT_RETRIES) {
    if (Date.now() > sweepDeadline) {
      deferred = due.length - i;
      log.warn('retry sweep hit deadline', { userId, processed: i, deferred });
      break;
    }
    const batch = due.slice(i, i + MAX_CONCURRENT_RETRIES);
    await Promise.all(batch.map(retryOne));
  }

  return { retried: due.length - deferred, ok, failed, deferred };
}

// --- Public entry ---------------------------------------------------------

export async function dispatchPlan(userId, { planId, target = 'preview', taskIds, config = {} }) {
  if (!ALLOWED_TARGETS.has(target)) {
    throw new Error(`Unknown dispatch target: ${target}`);
  }
  const plan = getPlan(userId, planId);
  if (!plan) throw new Error(`Plan ${planId} not found`);

  // Optional whitelist — if taskIds is provided, only dispatch those.
  // Useful when the user reviews the preview and wants to dispatch a
  // subset rather than the whole plan.
  let tasks = plan.tasks;
  if (Array.isArray(taskIds) && taskIds.length > 0) {
    const set = new Set(taskIds.map(String));
    tasks = tasks.filter((t) => set.has(t.id));
  }

  if (target === 'preview') {
    return { target, plan: { id: plan.id, title: plan.title }, results: dispatchPreview({ plan, tasks }) };
  }
  // Audit trail: every external dispatch logs who dispatched what,
  // where, and (below) how it went. Preview mode never reaches here.
  log.info('dispatch_plan_start', { userId, planId, target, taskCount: tasks.length });
  let raw;
  if (target === 'github')       raw = await dispatchGithub(userId, { plan, tasks, ...config });
  else if (target === 'backlog') raw = await dispatchBacklog(userId, { plan, tasks, ...config });
  else if (target === 'linear')  raw = await dispatchLinear(userId, { plan, tasks, ...config });
  else throw new Error('Unhandled dispatch target'); // should be unreachable

  const results = withRetryTracking(userId, target, raw);
  const counts = { ok: 0, errored: 0, skipped: 0 };
  for (const r of results) {
    if (r.status === 'ok') counts.ok += 1;
    else if (r.status === 'error') counts.errored += 1;
    else if (r.status === 'skipped') counts.skipped += 1;
  }
  log.info('dispatch_plan_result', { userId, planId, target, ...counts });
  return { target, plan: { id: plan.id, title: plan.title }, results };
}
