import SwiftUI
import WebKit

/// Renders an `.html` document as the page it is, rather than as source.
///
/// The counterpart to `MarkdownWebView`: both are the "professional preview"
/// half of a Preview/Raw pair (`EditableTextDetailView`), both open in preview
/// by default, and both send link clicks to the browser instead of navigating
/// the pane. The difference is that the markdown view OWNS its document (it
/// builds the HTML from `MarkdownRenderer`), while this one displays a
/// document the app did not write — typically generated by a model.
///
/// That is why the content policy is explicit here: scripts are allowed to run
/// (a generated deck, a chart, an interactive report is the point of previewing
/// HTML rather than reading its source), but everything the page could FETCH is
/// denied by an injected CSP — no remote scripts, stylesheets, images, fonts,
/// `fetch`/XHR/WebSocket, frames or plugins — and navigation out of the pane is
/// refused unless the user confirms the destination.
///
/// Two gaps worth naming rather than implying they are covered: CSP has no
/// directive for `RTCPeerConnection`, so a determined document could still
/// signal out over WebRTC; and a script can synthesise a link click, which is
/// why opening one asks first instead of launching the browser silently.
struct HtmlPreviewWebView: NSViewRepresentable {
    let html: String

    /// Inline scripts and styles run; every remote fetch is denied. `data:`
    /// and `blob:` stay allowed so a self-contained document can carry its own
    /// images and fonts inline, which is how a generated one usually ships.
    /// `base-uri 'none'` matters for the link path below: without it a
    /// `<base href="https://…">` silently repoints every relative link in the
    /// document at another host.
    static let contentSecurityPolicy = [
        "default-src 'none'",
        "script-src 'unsafe-inline' 'unsafe-eval' data: blob:",
        "style-src 'unsafe-inline' data:",
        "img-src data: blob:",
        "font-src data:",
        "media-src data: blob:",
        "form-action 'none'",
        "base-uri 'none'",
    ].joined(separator: "; ")

    /// Splice the policy into `document` as the FIRST thing in its head, so it
    /// is in force before any element that could start a load is parsed.
    ///
    /// A `<head>` is used when the document has one; otherwise the meta goes
    /// in front (an implicit head is created) — but AFTER a `<!DOCTYPE>` if
    /// there is one, because a doctype preceded by any content is ignored and
    /// the page would render in quirks mode.
    ///
    /// The insertion point is the end of the `<head …>` START TAG, not the
    /// literal string `<head>` — a generated document often writes
    /// `<head lang="ja">`. Matching a bare prefix is equally wrong in the
    /// other direction: `<header>` also starts with `<head`, and splicing the
    /// meta into the BODY means WebKit ignores the http-equiv entirely and
    /// the document then runs with no policy at all.
    static func withContentPolicy(_ document: String) -> String {
        let meta = #"<meta http-equiv="Content-Security-Policy" content="\#(contentSecurityPolicy)">"#
        if let tagEnd = headStartTagEnd(in: document) {
            return document.replacingCharacters(in: tagEnd..<tagEnd, with: meta)
        }
        guard let doctypeEnd = doctypeEnd(in: document) else { return meta + document }
        return document.replacingCharacters(in: doctypeEnd..<doctypeEnd, with: meta)
    }

    /// Index just past the `>` of the document's `<head …>` start tag, or nil
    /// when it has none. A match counts only when the character after `<head`
    /// ends the tag name (`>`, `/`, or whitespace) — that is what separates it
    /// from `<header>` — and only when it is not inside an HTML comment: a
    /// templated page often carries a `<!-- … -->` banner before `<html>`, and
    /// splicing the meta inside a comment leaves the document running with no
    /// policy at all, which is the failure this whole function exists to stop.
    private static func headStartTagEnd(in document: String) -> String.Index? {
        var searchFrom = document.startIndex
        while let match = document.range(of: "<head", options: .caseInsensitive,
                                         range: searchFrom..<document.endIndex) {
            guard match.upperBound < document.endIndex else { return nil }
            let next = document[match.upperBound]
            if next == ">" || next == "/" || next.isWhitespace,
               !isInsideComment(document, index: match.lowerBound),
               let close = document.range(of: ">", range: match.upperBound..<document.endIndex) {
                return close.upperBound
            }
            searchFrom = match.upperBound
        }
        return nil
    }

    /// Whether `index` sits inside a `<!-- … -->` span: the nearest `<!--`
    /// before it has no `-->` between that and `index`.
    private static func isInsideComment(_ document: String, index: String.Index) -> Bool {
        guard let open = document.range(of: "<!--", options: .backwards,
                                        range: document.startIndex..<index)
        else { return false }
        return document.range(of: "-->", range: open.upperBound..<index) == nil
    }

    /// Index just past the `>` of a leading `<!DOCTYPE …>`, or nil when the
    /// document does not open with one.
    private static func doctypeEnd(in document: String) -> String.Index? {
        let leading = document.drop { $0.isWhitespace }
        guard leading.prefix(9).lowercased() == "<!doctype",
              let close = document.range(of: ">", range: leading.startIndex..<document.endIndex)
        else { return nil }
        return close.upperBound
    }

    func makeCoordinator() -> Coordinator { Coordinator() }

    func makeNSView(context: Context) -> WKWebView {
        let config = WKWebViewConfiguration()
        // Nothing a previewed document does should survive it or be readable
        // by the next one.
        config.websiteDataStore = .nonPersistent()
        let webView = WKWebView(frame: .zero, configuration: config)
        webView.navigationDelegate = context.coordinator
        load(into: webView, context: context)
        return webView
    }

    func updateNSView(_ nsView: WKWebView, context: Context) {
        // Same reload guard as MarkdownWebView: a reload resets scroll
        // position, so it must happen only when the document actually changed.
        guard context.coordinator.lastHTML != html else { return }
        load(into: nsView, context: context)
    }

    private func load(into webView: WKWebView, context: Context) {
        let document = Self.withContentPolicy(html)
        context.coordinator.lastHTML = html
        context.coordinator.reload = { [weak coordinator = context.coordinator] web in
            // Re-arm HERE, not only in this function: the content-process
            // recovery path calls `reload` directly, so a rearm that lived
            // outside the closure would leave a recovered view silenced until
            // some later SwiftUI pass happened to come through `load`.
            coordinator?.rearmLinkPrompt()
            web.loadHTMLString(document, baseURL: nil)
        }
        context.coordinator.rearmLinkPrompt()
        // baseURL nil: the document is loaded as about:blank, so a relative
        // URL inside it resolves to nothing rather than to a file next to it.
        webView.loadHTMLString(document, baseURL: nil)
    }

    final class Coordinator: NSObject, WKNavigationDelegate {
        var lastHTML: String?
        /// Repaint after the system kills the content process under memory
        /// pressure — without it the pane stays blank, because the change
        /// guard above still matches. Same fix as `MarkdownWebView`.
        var reload: ((WKWebView) -> Void)?

        func webViewWebContentProcessDidTerminate(_ webView: WKWebView) {
            lastHTML = nil
            reload?(webView)
        }

        /// One outstanding confirmation at a time: a document that synthesises
        /// clicks in a loop must not be able to stack modal sheets.
        private var isAsking = false
        /// Set by the first Cancel. `NSAlert.runModal()` is APP-modal, so a
        /// document clicking in a loop would otherwise put up a fresh alert
        /// the instant the last one closed — the user could not switch file,
        /// close the tab, or quit. One refusal silences the rest of this
        /// document's navigation attempts; loading a different document (or
        /// the same one again) re-arms it.
        private var linkOpeningRefused = false

        func rearmLinkPrompt() { linkOpeningRefused = false }

        func webView(_ webView: WKWebView,
                     decidePolicyFor navigationAction: WKNavigationAction,
                     decisionHandler: @escaping (WKNavigationActionPolicy) -> Void) {
            // Only the about:blank load this view starts itself ever proceeds
            // in-pane. Everything else — a clicked link, a `location =`, a
            // meta refresh — is cancelled here.
            let isSelfLoad = navigationAction.request.url.map {
                $0.absoluteString == "about:blank" || $0.scheme == "about"
            } ?? true
            if isSelfLoad {
                decisionHandler(.allow)
                return
            }
            decisionHandler(.cancel)

            // A link may still be opened in the browser, but only after the
            // user confirms the destination.
            //
            // This is NOT the same deal `MarkdownWebView` offers, and the
            // difference is deliberate: scripts run here, and WebKit reports a
            // script-synthesised `a.click()` as `.linkActivated` exactly like
            // a human click. Opening on that signal alone would let a
            // previewed document push the text it was generated from into a
            // URL and launch the user's browser with it — an exfiltration path
            // that no CSP directive covers. Asking makes the attempt visible.
            guard navigationAction.navigationType == .linkActivated,
                  let url = navigationAction.request.url,
                  url.scheme == "http" || url.scheme == "https" || url.scheme == "mailto",
                  !isAsking, !linkOpeningRefused
            else { return }
            isAsking = true
            let alert = NSAlert()
            // The HOST goes in the title, where it cannot be pushed out of
            // sight: an exfiltration URL is long by construction, and a long
            // informative text is exactly where the real destination hides.
            // Host first, and the whole URL when there is no host (mailto:),
            // so the title never reads "Open mailto in your browser?".
            alert.messageText = "Open \(url.host ?? url.absoluteString) in your browser?"
            alert.informativeText = url.absoluteString
            alert.addButton(withTitle: "Open")
            alert.addButton(withTitle: "Cancel")
            let open = alert.runModal() == .alertFirstButtonReturn
            isAsking = false
            if open {
                NSWorkspace.shared.open(url)
            } else {
                linkOpeningRefused = true
            }
        }
    }
}
